### ISSUE TITLE
How to place placeholder in this one.  

### ISSUE THREAD

**Issue by praveenkumarrize** [TechnologyGeek12/react-geolocation-autosuggest#1]
![image](https://user-images.githubusercontent.com/50015149/60241035-fbb36100-98cf-11e9-9300-f99ec2da4ad1.png)

**Comment by navdeepgarg1** [comment]
Hi @praveenkumarrize  thanks for you time and reporting it.
This contains floating labels from material-ui, which works as a label and placeholder both , so can't add placeholder separately.
For more info you can check material-ui floating label in fields.

Thanks

**Comment by TechnologyGeek12** [comment]
Hi @praveenkumarrize thanks for you time and reporting it.
This contains floating labels from material-ui, which works as a label and placeholder both , so can't add placeholder separately.
For more info you can check material-ui floating label in fields.

Thanks
